import Head from "next/head";
// import ChatInterface from "../components/ChatInterface";
// import { ModeToggle } from "@/components/mode-toggle";
import { Authentication } from "@/components/Authentication";

import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  if (!session) {
    // Handle unauthenticated state, e.g. render a SignIn component
    return <Authentication />;
  }
  return (
    <>
      <Head>
        <title>speak to order</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>hello</div>
    </>
  );
}
