import Head from "next/head";
// import ChatInterface from "../components/ChatInterface";
// import { ModeToggle } from "@/components/mode-toggle";
export default function Home() {
  return (
    <>
      <Head>
        <title>speak to order</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>hello</div>
    </>
  );
}
