import Head from "next/head";
import ChatInterface from "../components/ChatInterface";
import { ModeToggle } from "@/components/mode-toggle";
export default function Home() {
  return (
    <>
      <Head>
        <title>speak to order</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <main className="mx-auto max-w-3xl">
          <header className="flex w-full items-center">
            <h1>speak to order</h1>
            <ModeToggle />
          </header>
        </main>
      </div>
    </>
  );
}
